local opt = vim.opt

opt.termguicolors = true
opt.background = "dark"
opt.signcolumn = "yes"
opt.relativenumber = true
opt.number = true
opt.tabstop = 2
opt.shiftwidth = 2
opt.expandtab = true
opt.autoindent = true
opt.cursorline = true
opt.splitright = true
opt.splitbelow = true
opt.showmode = false
opt.fileencoding = "utf-8"
opt.swapfile = false
opt.undodir = "/tmp/.nvimdid"
opt.undofile = true
opt.undolevels = 1000
opt.undoreload = 10000

-- opt.backup = false
-- opt.hlsearch = true
-- opt.incsearch = true
-- opt.scrolloff = 5
-- opt.sidescrolloff = 5
-- opt.smartindent = true
-- opt.hidden = true
-- opt.ignorecase = true
-- opt.timeoutlen = 1000
-- opt.shiftround = true
-- opt.smartcase = true
-- opt.mouse = "a"
-- opt.cmdheight = 1
-- opt.pumheight = 10
-- opt.laststatus = 3
-- opt.updatetime = 250
