local Plug = vim.fn['plug#']

vim.call('plug#begin', '~/.config/nvim/plugged')
  Plug('/usr/local/opt/fzf')
  Plug('junegunn/fzf', {['do'] = vim.fn['fzf#install']})
  Plug('junegunn/fzf.vim')
  Plug('scrooloose/nerdtree')
  Plug('JamshedVesuna/vim-markdown-preview')
  Plug('christoomey/vim-tmux-navigator')
  Plug('benmills/vimux')
  Plug('airblade/vim-gitgutter')
  Plug('tpope/vim-fugitive')
  Plug('arcticicestudio/nord-vim')
  Plug('vim-airline/vim-airline')
  Plug('ryanoasis/vim-devicons')
  Plug('tpope/vim-commentary')
  Plug('tpope/vim-sensible')
  Plug('tpope/vim-bundler')
  Plug('tpope/vim-rails')
  Plug('Raimondi/delimitMate')
  Plug('Yggdroot/indentLine')
  Plug('qpkorr/vim-bufkill')
  Plug('sheerun/vim-polyglot')
vim.call('plug#end')
